--------------------------------------------------------
--  DDL for Table ATTENDANCE_MAS
--------------------------------------------------------

  CREATE TABLE "HR"."ATTENDANCE_MAS" 
   (	"SEQNO" NUMBER, 
	"ENTITY_ID" NUMBER, 
	"ENTITY_TYPE_ID" NUMBER, 
	"ATTENDANCE_DATE" DATE, 
	"ATTENDANCE_TIME" DATE, 
	"ENT_DATE" DATE, 
	"ENT_USER" VARCHAR2(30 BYTE), 
	"ENT_TERM" VARCHAR2(30 BYTE), 
	"UPD_DATE" DATE, 
	"UPD_USER" VARCHAR2(30 BYTE), 
	"UPD_TERM" VARCHAR2(30 BYTE), 
	"TIME_STAMP" VARCHAR2(50 BYTE), 
	"FLG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"BATCH_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
