--------------------------------------------------------
--  Constraints for Table ATTENDANCE_MAS
--------------------------------------------------------

  ALTER TABLE "HR"."ATTENDANCE_MAS" ADD CONSTRAINT "ATTENDANCE_MAS_PK" PRIMARY KEY ("SEQNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."ATTENDANCE_MAS" MODIFY ("SEQNO" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."ATTENDANCE_MAS" MODIFY ("ENTITY_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."ATTENDANCE_MAS" MODIFY ("ENTITY_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."ATTENDANCE_MAS" MODIFY ("ATTENDANCE_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."ATTENDANCE_MAS" MODIFY ("ATTENDANCE_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."ATTENDANCE_MAS" MODIFY ("ENT_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."ATTENDANCE_MAS" MODIFY ("ENT_USER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."ATTENDANCE_MAS" MODIFY ("ENT_TERM" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."ATTENDANCE_MAS" MODIFY ("TIME_STAMP" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."ATTENDANCE_MAS" MODIFY ("FLG" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."ATTENDANCE_MAS" MODIFY ("BATCH_ID" NOT NULL ENABLE);
