--------------------------------------------------------
--  DDL for Table CHP_DET
--------------------------------------------------------

  CREATE TABLE "HR"."CHP_DET" 
   (	"SEQNO" NUMBER(5,0), 
	"REF_SUB_ID" NUMBER, 
	"CHP_ID" NUMBER, 
	"CHP_NAME" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"REMARK" VARCHAR2(100 BYTE), 
	"ENT_DATE" DATE, 
	"ENT_USER" VARCHAR2(20 BYTE), 
	"ENT_TERM" VARCHAR2(20 BYTE), 
	"UPD_DATE" DATE, 
	"UPD_USER" VARCHAR2(20 BYTE), 
	"UPD_TERM" VARCHAR2(20 BYTE), 
	"TIME_STAMP" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
