--------------------------------------------------------
--  Constraints for Table CHP_DET
--------------------------------------------------------

  ALTER TABLE "HR"."CHP_DET" ADD CONSTRAINT "CHAP_DET_PK" PRIMARY KEY ("SEQNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."CHP_DET" ADD CONSTRAINT "CHP_DET_UK1" UNIQUE ("REF_SUB_ID", "CHP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."CHP_DET" MODIFY ("SEQNO" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."CHP_DET" MODIFY ("REF_SUB_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."CHP_DET" MODIFY ("CHP_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."CHP_DET" MODIFY ("CHP_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."CHP_DET" MODIFY ("TIME_STAMP" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."CHP_DET" MODIFY ("ENT_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."CHP_DET" MODIFY ("ENT_USER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."CHP_DET" MODIFY ("ENT_TERM" NOT NULL ENABLE);
