--------------------------------------------------------
--  DDL for Table EMP_MAS
--------------------------------------------------------

  CREATE TABLE "HR"."EMP_MAS" 
   (	"BRANCH" VARCHAR2(20 BYTE), 
	"ENTITY_ID" NUMBER(4,0), 
	"GR_NO" NUMBER(4,0), 
	"F_NAME" VARCHAR2(20 BYTE), 
	"M_NAME" VARCHAR2(20 BYTE), 
	"L_NAME" VARCHAR2(20 BYTE), 
	"DOB" DATE, 
	"DOJ" DATE, 
	"LEAVE_DATE" DATE, 
	"SEX" VARCHAR2(1 BYTE), 
	"BLOOD_GRP" VARCHAR2(10 BYTE), 
	"PHONE1" NUMBER(10,0), 
	"PHONE2" NUMBER(10,0), 
	"PHOTO" CLOB, 
	"ADD1" VARCHAR2(100 BYTE), 
	"ADD2" VARCHAR2(100 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(20 BYTE), 
	"PINCODE" NUMBER(10,0), 
	"EMAIL_ID" VARCHAR2(50 BYTE), 
	"ENT_DATE" VARCHAR2(30 BYTE), 
	"ENT_USER" VARCHAR2(30 BYTE), 
	"ENT_TERM" VARCHAR2(30 BYTE), 
	"UPD_DATE" DATE, 
	"UPD_USER" VARCHAR2(30 BYTE), 
	"UPD_TERM" VARCHAR2(30 BYTE), 
	"TIME_STAMP" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PHOTO") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

   COMMENT ON COLUMN "HR"."EMP_MAS"."GR_NO" IS 'GENRAL NUMBER';
