REM INSERTING into HR.ENTITY_TYPE_MAS
SET DEFINE OFF;
Insert into HR.ENTITY_TYPE_MAS (ENTITY_TYPE_ID,ENTITY_TYPE_NAME,IS_ACTIVE,ENT_DATE,ENT_USER,ENT_TERM,UPD_DATE,UPD_USER,UPD_TERM,TIME_STAMP) values (1,'STUDENT','Y',to_date('11-07-15','DD-MM-RR'),'RLT','RAHUL-PC',null,null,null,to_timestamp('11-07-15 08:03:09.049000000 AM','DD-MM-RR HH12:MI:SSXFF AM'));
Insert into HR.ENTITY_TYPE_MAS (ENTITY_TYPE_ID,ENTITY_TYPE_NAME,IS_ACTIVE,ENT_DATE,ENT_USER,ENT_TERM,UPD_DATE,UPD_USER,UPD_TERM,TIME_STAMP) values (2,'TEACHER','Y',to_date('11-07-15','DD-MM-RR'),'RLT','RAHUL-PC',null,null,null,to_timestamp('11-07-15 08:03:38.185000000 AM','DD-MM-RR HH12:MI:SSXFF AM'));
