--------------------------------------------------------
--  Constraints for Table EXAM_MAS
--------------------------------------------------------

  ALTER TABLE "HR"."EXAM_MAS" ADD CONSTRAINT "EXAM_MAS_PK" PRIMARY KEY ("BATCH_ID", "REF_SUB_ID", "EXAM_DATE", "EXAM_TIME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."EXAM_MAS" ADD CONSTRAINT "EXAM_MAS_UK_ID" UNIQUE ("EXAM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."EXAM_MAS" MODIFY ("BRANCH" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."EXAM_MAS" MODIFY ("BATCH_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."EXAM_MAS" MODIFY ("EXAM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."EXAM_MAS" MODIFY ("REF_SUB_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."EXAM_MAS" MODIFY ("TOTAL_MARK" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."EXAM_MAS" MODIFY ("EXAM_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."EXAM_MAS" MODIFY ("TYPE_DET" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."EXAM_MAS" MODIFY ("EXAM_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."EXAM_MAS" MODIFY ("EXAM_TIME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."EXAM_MAS" MODIFY ("ENT_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."EXAM_MAS" MODIFY ("ENT_TERM" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."EXAM_MAS" MODIFY ("ENT_USER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."EXAM_MAS" MODIFY ("TIME_STAMP" NOT NULL ENABLE);
