--------------------------------------------------------
--  DDL for Table EXAM_MAS
--------------------------------------------------------

  CREATE TABLE "HR"."EXAM_MAS" 
   (	"BRANCH" VARCHAR2(10 BYTE), 
	"BATCH_ID" NUMBER, 
	"EXAM_ID" NUMBER, 
	"REF_SUB_ID" NUMBER, 
	"TOTAL_MARK" NUMBER, 
	"EXAM_TYPE" VARCHAR2(10 BYTE), 
	"TYPE_DET" VARCHAR2(10 BYTE), 
	"PAPER_SET_BY" VARCHAR2(50 BYTE), 
	"EXAM_DATE" DATE, 
	"EXAM_TIME" VARCHAR2(20 BYTE), 
	"DURATION" VARCHAR2(50 BYTE), 
	"SUPERVISOR" VARCHAR2(50 BYTE), 
	"ENT_DATE" DATE, 
	"ENT_TERM" VARCHAR2(20 BYTE), 
	"ENT_USER" VARCHAR2(20 BYTE), 
	"UPD_DATE" DATE, 
	"UPD_USER" VARCHAR2(20 BYTE), 
	"UPD_TERM" VARCHAR2(20 BYTE), 
	"TIME_STAMP" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "HR"."EXAM_MAS"."EXAM_TYPE" IS '(MCQ/THEORY)
';
 
   COMMENT ON COLUMN "HR"."EXAM_MAS"."TYPE_DET" IS '(CHAPTER/FULL)
';
