--------------------------------------------------------
--  Constraints for Table FLG_MAS
--------------------------------------------------------

  ALTER TABLE "HR"."FLG_MAS" ADD CONSTRAINT "FLG_MAS_PK" PRIMARY KEY ("FLG_ID", "FLG_SH_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."FLG_MAS" MODIFY ("FLG_SH_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."FLG_MAS" MODIFY ("FLG_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."FLG_MAS" MODIFY ("FLG_ID" NOT NULL ENABLE);
