--------------------------------------------------------
--  DDL for Table FLG_MAS
--------------------------------------------------------

  CREATE TABLE "HR"."FLG_MAS" 
   (	"FLG_ID" NUMBER, 
	"FLG_SH_NAME" VARCHAR2(20 BYTE), 
	"FLG_NAME" VARCHAR2(20 BYTE), 
	"REMARK" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
