--------------------------------------------------------
--  File created - Thursday-October-08-2015   
--------------------------------------------------------
@E:\Study\Github Projects\tuition_orcl\DEPARTMENTS_SEQ.sql
@E:\Study\Github Projects\tuition_orcl\EMPLOYEES_SEQ.sql
@E:\Study\Github Projects\tuition_orcl\LOCATIONS_SEQ.sql
@E:\Study\Github Projects\tuition_orcl\SEQ_ENTITY_ID.sql
@E:\Study\Github Projects\tuition_orcl\ATTENDANCE_MAS.sql
@E:\Study\Github Projects\tuition_orcl\BATCH_MAS.sql
@E:\Study\Github Projects\tuition_orcl\BRANCH_MAS.sql
@E:\Study\Github Projects\tuition_orcl\CHP_DET.sql
@E:\Study\Github Projects\tuition_orcl\EMP_MAS.sql
@E:\Study\Github Projects\tuition_orcl\ENTITY_MAS.sql
@E:\Study\Github Projects\tuition_orcl\ENTITY_TYPE_MAS.sql
@E:\Study\Github Projects\tuition_orcl\EXAM_MAS.sql
@E:\Study\Github Projects\tuition_orcl\FLG_MAS.sql
@E:\Study\Github Projects\tuition_orcl\GRID_FIELDS.sql
@E:\Study\Github Projects\tuition_orcl\MONEY_FLOW.sql
@E:\Study\Github Projects\tuition_orcl\RESULT_MAS.sql
@E:\Study\Github Projects\tuition_orcl\SCHL_MAS.sql
@E:\Study\Github Projects\tuition_orcl\STATIC_COMBO.sql
@E:\Study\Github Projects\tuition_orcl\STUDY_LEVEL_MAS.sql
@E:\Study\Github Projects\tuition_orcl\STUD_MAS.sql
@E:\Study\Github Projects\tuition_orcl\SUB_ALLOCATION.sql
@E:\Study\Github Projects\tuition_orcl\SUB_MAS.sql
@E:\Study\Github Projects\tuition_orcl\TEACHER_MAS.sql
@E:\Study\Github Projects\tuition_orcl\TIMETABLE.sql
@E:\Study\Github Projects\tuition_orcl\TRANSACTION_SETTING.sql
@E:\Study\Github Projects\tuition_orcl\EMP_DETAILS_VIEW.sql
@E:\Study\Github Projects\tuition_orcl\ATTENDANCE_MAS_DATA_TABLE.sql
@E:\Study\Github Projects\tuition_orcl\BATCH_MAS_DATA_TABLE.sql
@E:\Study\Github Projects\tuition_orcl\BRANCH_MAS_DATA_TABLE.sql
@E:\Study\Github Projects\tuition_orcl\CHP_DET_DATA_TABLE.sql
@E:\Study\Github Projects\tuition_orcl\EMP_MAS_DATA_TABLE.sql
@E:\Study\Github Projects\tuition_orcl\ENTITY_MAS_DATA_TABLE.sql
@E:\Study\Github Projects\tuition_orcl\ENTITY_TYPE_MAS_DATA_TABLE.sql
@E:\Study\Github Projects\tuition_orcl\EXAM_MAS_DATA_TABLE.sql
@E:\Study\Github Projects\tuition_orcl\FLG_MAS_DATA_TABLE.sql
@E:\Study\Github Projects\tuition_orcl\GRID_FIELDS_DATA_TABLE.sql
@E:\Study\Github Projects\tuition_orcl\MONEY_FLOW_DATA_TABLE.sql
@E:\Study\Github Projects\tuition_orcl\RESULT_MAS_DATA_TABLE.sql
@E:\Study\Github Projects\tuition_orcl\SCHL_MAS_DATA_TABLE.sql
@E:\Study\Github Projects\tuition_orcl\STATIC_COMBO_DATA_TABLE.sql
@E:\Study\Github Projects\tuition_orcl\STUDY_LEVEL_MAS_DATA_TABLE.sql
@E:\Study\Github Projects\tuition_orcl\STUD_MAS_DATA_TABLE.sql
@E:\Study\Github Projects\tuition_orcl\SUB_ALLOCATION_DATA_TABLE.sql
@E:\Study\Github Projects\tuition_orcl\SUB_MAS_DATA_TABLE.sql
@E:\Study\Github Projects\tuition_orcl\TEACHER_MAS_DATA_TABLE.sql
@E:\Study\Github Projects\tuition_orcl\TIMETABLE_DATA_TABLE.sql
@E:\Study\Github Projects\tuition_orcl\TRANSACTION_SETTING_DATA_TABLE.sql
@E:\Study\Github Projects\tuition_orcl\UK1.sql
@E:\Study\Github Projects\tuition_orcl\MONEY_FLOW_PK.sql
@E:\Study\Github Projects\tuition_orcl\SUB_ALLOCATION_UK1.sql
@E:\Study\Github Projects\tuition_orcl\TRANSACTION_SETTING_UK1.sql
@E:\Study\Github Projects\tuition_orcl\UK_ENTITY_ID.sql
@E:\Study\Github Projects\tuition_orcl\ATTENDANCE_MAS_PK.sql
@E:\Study\Github Projects\tuition_orcl\UK_STD_ID.sql
@E:\Study\Github Projects\tuition_orcl\STUDY_LEVEL_MAS_PK.sql
@E:\Study\Github Projects\tuition_orcl\TRANSACTION_SETTING_PK.sql
@E:\Study\Github Projects\tuition_orcl\UK_SUB_ID.sql
@E:\Study\Github Projects\tuition_orcl\UK_STD_SUB_ID.sql
@E:\Study\Github Projects\tuition_orcl\SUB_ALLOCATION_PK.sql
@E:\Study\Github Projects\tuition_orcl\ENTITY_MAS_PK.sql
@E:\Study\Github Projects\tuition_orcl\ENTITY_MAS_UK1.sql
@E:\Study\Github Projects\tuition_orcl\RESULT_MAS_PK.sql
@E:\Study\Github Projects\tuition_orcl\BATCH_MAS_PK.sql
@E:\Study\Github Projects\tuition_orcl\CHAP_DET_PK.sql
@E:\Study\Github Projects\tuition_orcl\ENTITY_TYPE_MAS_PK.sql
@E:\Study\Github Projects\tuition_orcl\EMP_MAS_PK.sql
@E:\Study\Github Projects\tuition_orcl\UK_ENTITY_TYPE_ID.sql
@E:\Study\Github Projects\tuition_orcl\STATIC_COMBO_PK.sql
@E:\Study\Github Projects\tuition_orcl\FLG_MAS_PK.sql
@E:\Study\Github Projects\tuition_orcl\UK_BATCH_ID.sql
@E:\Study\Github Projects\tuition_orcl\RESULT_MAS_UK1.sql
@E:\Study\Github Projects\tuition_orcl\CHP_DET_UK1.sql
@E:\Study\Github Projects\tuition_orcl\PK1.sql
@E:\Study\Github Projects\tuition_orcl\SUB_MAS_PK.sql
@E:\Study\Github Projects\tuition_orcl\TIMETABLE_UK1.sql
@E:\Study\Github Projects\tuition_orcl\SCHL_MAS_PK.sql
@E:\Study\Github Projects\tuition_orcl\SCHL_MAS_CONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\RESULT_MAS_CONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\STUD_MAS_CONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\ENTITY_TYPE_MAS_CONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\CHP_DET_CONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\EXAM_MAS_CONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\TRANSACTION_SETTING_CONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\FLG_MAS_CONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\GRID_FIELDS_CONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\EMP_MAS_CONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\SUB_ALLOCATION_CONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\STUDY_LEVEL_MAS_CONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\ATTENDANCE_MAS_CONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\ENTITY_MAS_CONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\TEACHER_MAS_CONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\BRANCH_MAS_CONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\SUB_MAS_CONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\MONEY_FLOW_CONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\TIMETABLE_CONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\STATIC_COMBO_CONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\BATCH_MAS_CONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\ATTENDANCE_MAS_REFCONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\BATCH_MAS_REFCONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\CHP_DET_REFCONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\ENTITY_MAS_REFCONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\EXAM_MAS_REFCONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\MONEY_FLOW_REFCONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\RESULT_MAS_REFCONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\SUB_ALLOCATION_REFCONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\TIMETABLE_REFCONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\TRANSACTION_SETTING_REFCONSTRAINT.sql
@E:\Study\Github Projects\tuition_orcl\PKG_ATTENDANCE_MAS.sql
@E:\Study\Github Projects\tuition_orcl\PKG_BATCH_MAS.sql
@E:\Study\Github Projects\tuition_orcl\PKG_CHP_DET.sql
@E:\Study\Github Projects\tuition_orcl\PKG_EMP_MAS.sql
@E:\Study\Github Projects\tuition_orcl\PKG_ENTITY_TYPE_MAS.sql
@E:\Study\Github Projects\tuition_orcl\PKG_EXAM_MAS.sql
@E:\Study\Github Projects\tuition_orcl\PKG_GRIDFIELD_MAS.sql
@E:\Study\Github Projects\tuition_orcl\PKG_MONEY_FLOW.sql
@E:\Study\Github Projects\tuition_orcl\PKG_RESULT_MAS.sql
@E:\Study\Github Projects\tuition_orcl\PKG_STUDY_LEVEL_MAS.sql
@E:\Study\Github Projects\tuition_orcl\PKG_SUB_ALLOCATION.sql
@E:\Study\Github Projects\tuition_orcl\PKG_SUB_MAS.sql
@E:\Study\Github Projects\tuition_orcl\PKG_TIMETABLE.sql
@E:\Study\Github Projects\tuition_orcl\PKG_TRANSACTION_SETTING.sql
@E:\Study\Github Projects\tuition_orcl\PKG_TUITION_BASE.sql
@E:\Study\Github Projects\tuition_orcl\PKG_ATTENDANCE_MAS_1.sql
@E:\Study\Github Projects\tuition_orcl\PKG_BATCH_MAS_1.sql
@E:\Study\Github Projects\tuition_orcl\PKG_CHP_DET_1.sql
@E:\Study\Github Projects\tuition_orcl\PKG_EMP_MAS_1.sql
@E:\Study\Github Projects\tuition_orcl\PKG_ENTITY_TYPE_MAS_1.sql
@E:\Study\Github Projects\tuition_orcl\PKG_EXAM_MAS_1.sql
@E:\Study\Github Projects\tuition_orcl\PKG_GRIDFIELD_MAS_1.sql
@E:\Study\Github Projects\tuition_orcl\PKG_MONEY_FLOW_1.sql
@E:\Study\Github Projects\tuition_orcl\PKG_RESULT_MAS_1.sql
@E:\Study\Github Projects\tuition_orcl\PKG_STUDY_LEVEL_MAS_1.sql
@E:\Study\Github Projects\tuition_orcl\PKG_SUB_ALLOCATION_1.sql
@E:\Study\Github Projects\tuition_orcl\PKG_SUB_MAS_1.sql
@E:\Study\Github Projects\tuition_orcl\PKG_TIMETABLE_1.sql
@E:\Study\Github Projects\tuition_orcl\PKG_TRANSACTION_SETTING_1.sql
@E:\Study\Github Projects\tuition_orcl\PKG_TUITION_BASE_1.sql
@E:\Study\Github Projects\tuition_orcl\ADD_JOB_HISTORY.sql
@E:\Study\Github Projects\tuition_orcl\SECURE_DML.sql
