--------------------------------------------------------
--  Constraints for Table MONEY_FLOW
--------------------------------------------------------

  ALTER TABLE "HR"."MONEY_FLOW" ADD CONSTRAINT "MONEY_FLOW_PK" PRIMARY KEY ("BRANCH", "TRN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."MONEY_FLOW" MODIFY ("BRANCH" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."MONEY_FLOW" MODIFY ("TRN_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."MONEY_FLOW" MODIFY ("AMT" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."MONEY_FLOW" MODIFY ("ENT_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."MONEY_FLOW" MODIFY ("ENT_TERM" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."MONEY_FLOW" MODIFY ("ENT_USER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."MONEY_FLOW" MODIFY ("TIME_STAMP" NOT NULL ENABLE);
