--------------------------------------------------------
--  Ref Constraints for Table MONEY_FLOW
--------------------------------------------------------

  ALTER TABLE "HR"."MONEY_FLOW" ADD CONSTRAINT "MONEY_FLOW_FK_FROM_ID" FOREIGN KEY ("FROM_ENTITY_ID")
	  REFERENCES "HR"."ENTITY_MAS" ("ENTITY_ID") ENABLE;
 
  ALTER TABLE "HR"."MONEY_FLOW" ADD CONSTRAINT "MONEY_FLOW_FK_FROM_TYPE" FOREIGN KEY ("FROM_TYPE")
	  REFERENCES "HR"."ENTITY_TYPE_MAS" ("ENTITY_TYPE_ID") ENABLE;
 
  ALTER TABLE "HR"."MONEY_FLOW" ADD CONSTRAINT "MONEY_FLOW_FK_TO_ID" FOREIGN KEY ("TO_ENTITY_ID")
	  REFERENCES "HR"."ENTITY_MAS" ("ENTITY_ID") ENABLE;
 
  ALTER TABLE "HR"."MONEY_FLOW" ADD CONSTRAINT "MONEY_FLOW_FK_TO_TYPE" FOREIGN KEY ("TO_TYPE")
	  REFERENCES "HR"."ENTITY_TYPE_MAS" ("ENTITY_TYPE_ID") ENABLE;
