--------------------------------------------------------
--  Constraints for Table SCHL_MAS
--------------------------------------------------------

  ALTER TABLE "HR"."SCHL_MAS" ADD CONSTRAINT "SCHL_MAS_PK" PRIMARY KEY ("SCHL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."SCHL_MAS" MODIFY ("SCHL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."SCHL_MAS" MODIFY ("ENT_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."SCHL_MAS" MODIFY ("ENT_USER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."SCHL_MAS" MODIFY ("ENT_TERM" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."SCHL_MAS" MODIFY ("TIME_STAMP" NOT NULL ENABLE);
