REM INSERTING into HR.STATIC_COMBO
SET DEFINE OFF;
Insert into HR.STATIC_COMBO (SRNO,DISP_MEM,VALUE_MEM,REF_SRNO,ORD) values (1,'STDTYP',null,-1,null);
Insert into HR.STATIC_COMBO (SRNO,DISP_MEM,VALUE_MEM,REF_SRNO,ORD) values (2,'GUJARATI','1',1,'1');
Insert into HR.STATIC_COMBO (SRNO,DISP_MEM,VALUE_MEM,REF_SRNO,ORD) values (3,'ENGLISH','2',1,'2');
Insert into HR.STATIC_COMBO (SRNO,DISP_MEM,VALUE_MEM,REF_SRNO,ORD) values (4,'STDMED',null,-1,null);
Insert into HR.STATIC_COMBO (SRNO,DISP_MEM,VALUE_MEM,REF_SRNO,ORD) values (5,'GSEB','1',4,'1');
Insert into HR.STATIC_COMBO (SRNO,DISP_MEM,VALUE_MEM,REF_SRNO,ORD) values (6,'CBSE','2',4,'2');
Insert into HR.STATIC_COMBO (SRNO,DISP_MEM,VALUE_MEM,REF_SRNO,ORD) values (7,'ICSE','3',4,'3');
Insert into HR.STATIC_COMBO (SRNO,DISP_MEM,VALUE_MEM,REF_SRNO,ORD) values (8,'EXAMTYPE',null,-1,null);
Insert into HR.STATIC_COMBO (SRNO,DISP_MEM,VALUE_MEM,REF_SRNO,ORD) values (9,'MCQ','1',8,'1');
Insert into HR.STATIC_COMBO (SRNO,DISP_MEM,VALUE_MEM,REF_SRNO,ORD) values (10,'THEORY','2',8,'2');
Insert into HR.STATIC_COMBO (SRNO,DISP_MEM,VALUE_MEM,REF_SRNO,ORD) values (11,'TRNTYPE',null,-1,null);
Insert into HR.STATIC_COMBO (SRNO,DISP_MEM,VALUE_MEM,REF_SRNO,ORD) values (12,'IN','1',11,'1');
Insert into HR.STATIC_COMBO (SRNO,DISP_MEM,VALUE_MEM,REF_SRNO,ORD) values (13,'OUT','2',11,'2');
Insert into HR.STATIC_COMBO (SRNO,DISP_MEM,VALUE_MEM,REF_SRNO,ORD) values (14,'EXAMTYPEDET',null,-1,null);
Insert into HR.STATIC_COMBO (SRNO,DISP_MEM,VALUE_MEM,REF_SRNO,ORD) values (15,'CHAPTER','1',14,'1');
Insert into HR.STATIC_COMBO (SRNO,DISP_MEM,VALUE_MEM,REF_SRNO,ORD) values (16,'FULL','2',14,'2');
