--------------------------------------------------------
--  DDL for Table STATIC_COMBO
--------------------------------------------------------

  CREATE TABLE "HR"."STATIC_COMBO" 
   (	"SRNO" NUMBER, 
	"DISP_MEM" VARCHAR2(20 BYTE), 
	"VALUE_MEM" VARCHAR2(20 BYTE), 
	"REF_SRNO" NUMBER, 
	"ORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
