--------------------------------------------------------
--  Constraints for Table STATIC_COMBO
--------------------------------------------------------

  ALTER TABLE "HR"."STATIC_COMBO" ADD CONSTRAINT "STATIC_COMBO_PK" PRIMARY KEY ("SRNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."STATIC_COMBO" MODIFY ("SRNO" NOT NULL ENABLE);
