REM INSERTING into HR.STUDY_LEVEL_MAS
SET DEFINE OFF;
Insert into HR.STUDY_LEVEL_MAS (BRANCH,STD_ID,STD_LEVEL,STD_TYPE,STD_NAME,IS_ACTIVE,ENT_DATE,ENT_USER,ENT_TERM,UPD_DATE,UPD_USER,UPD_TERM,TIME_STAMP,STD_MEDIUM) values ('TestBranch',1,11,'1',' 11th Sci','Y',to_date('04-10-15','DD-MM-RR'),'TestUser','RAHUL-PC',null,null,null,'04-OCT-15 07.32.37.159000 PM +05:30',1);
Insert into HR.STUDY_LEVEL_MAS (BRANCH,STD_ID,STD_LEVEL,STD_TYPE,STD_NAME,IS_ACTIVE,ENT_DATE,ENT_USER,ENT_TERM,UPD_DATE,UPD_USER,UPD_TERM,TIME_STAMP,STD_MEDIUM) values ('TestBranch',2,12,'2','12th sci','Y',to_date('04-10-15','DD-MM-RR'),'TestUser','RAHUL-PC',null,null,null,'04-OCT-15 07.32.37.191000 PM +05:30',1);
