--------------------------------------------------------
--  Constraints for Table STUD_MAS
--------------------------------------------------------

  ALTER TABLE "HR"."STUD_MAS" MODIFY ("STUD_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."STUD_MAS" MODIFY ("S_ENTITY_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."STUD_MAS" MODIFY ("S_FNAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."STUD_MAS" MODIFY ("PH1" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."STUD_MAS" MODIFY ("ENT_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."STUD_MAS" MODIFY ("ENT_USER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."STUD_MAS" MODIFY ("ENT_TERM" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."STUD_MAS" MODIFY ("TIME_STAMP" NOT NULL ENABLE);
