--------------------------------------------------------
--  Constraints for Table STUDY_LEVEL_MAS
--------------------------------------------------------

  ALTER TABLE "HR"."STUDY_LEVEL_MAS" ADD CONSTRAINT "STUDY_LEVEL_MAS_PK" PRIMARY KEY ("STD_ID", "BRANCH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."STUDY_LEVEL_MAS" MODIFY ("BRANCH" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."STUDY_LEVEL_MAS" MODIFY ("STD_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."STUDY_LEVEL_MAS" MODIFY ("STD_LEVEL" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."STUDY_LEVEL_MAS" MODIFY ("STD_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."STUDY_LEVEL_MAS" MODIFY ("ENT_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."STUDY_LEVEL_MAS" MODIFY ("ENT_USER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."STUDY_LEVEL_MAS" MODIFY ("ENT_TERM" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."STUDY_LEVEL_MAS" MODIFY ("TIME_STAMP" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."STUDY_LEVEL_MAS" ADD CONSTRAINT "UK_STD_ID" UNIQUE ("STD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
