--------------------------------------------------------
--  DDL for Table STUDY_LEVEL_MAS
--------------------------------------------------------

  CREATE TABLE "HR"."STUDY_LEVEL_MAS" 
   (	"BRANCH" VARCHAR2(30 BYTE), 
	"STD_ID" NUMBER, 
	"STD_LEVEL" NUMBER, 
	"STD_TYPE" VARCHAR2(6 BYTE), 
	"STD_NAME" VARCHAR2(40 BYTE), 
	"IS_ACTIVE" VARCHAR2(1 BYTE), 
	"ENT_DATE" DATE, 
	"ENT_USER" VARCHAR2(30 BYTE), 
	"ENT_TERM" VARCHAR2(30 BYTE), 
	"UPD_DATE" DATE, 
	"UPD_USER" VARCHAR2(30 BYTE), 
	"UPD_TERM" VARCHAR2(30 BYTE), 
	"TIME_STAMP" VARCHAR2(50 BYTE), 
	"STD_MEDIUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "HR"."STUDY_LEVEL_MAS"."STD_TYPE" IS 'GBSE\CBSE\ICSE';
