--------------------------------------------------------
--  Constraints for Table SUB_MAS
--------------------------------------------------------

  ALTER TABLE "HR"."SUB_MAS" ADD CONSTRAINT "SUB_MAS_PK" PRIMARY KEY ("SUB_ID", "BRANCH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."SUB_MAS" MODIFY ("BRANCH" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."SUB_MAS" MODIFY ("REF_STD_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."SUB_MAS" MODIFY ("HAVE_EXAM" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."SUB_MAS" MODIFY ("IS_ACTIVE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."SUB_MAS" MODIFY ("ENT_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."SUB_MAS" MODIFY ("ENT_TERM" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."SUB_MAS" MODIFY ("ENT_USER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."SUB_MAS" MODIFY ("TIME_STAMP" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."SUB_MAS" MODIFY ("SUB_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."SUB_MAS" ADD CONSTRAINT "UK_STD_SUB_ID" UNIQUE ("REF_STD_ID", "SUB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."SUB_MAS" ADD CONSTRAINT "UK_SUB_ID" UNIQUE ("SUB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
