--------------------------------------------------------
--  Constraints for Table SUB_ALLOCATION
--------------------------------------------------------

  ALTER TABLE "HR"."SUB_ALLOCATION" ADD CONSTRAINT "SUB_ALLOCATION_PK" PRIMARY KEY ("BRANCH", "ALLOCATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."SUB_ALLOCATION" ADD CONSTRAINT "SUB_ALLOCATION_UK1" UNIQUE ("BATCH_ID", "ENTITY_ID", "ENTITY_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."SUB_ALLOCATION" MODIFY ("ENT_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."SUB_ALLOCATION" MODIFY ("ENT_TERM" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."SUB_ALLOCATION" MODIFY ("ENT_USER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."SUB_ALLOCATION" MODIFY ("TIME_STAMP" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."SUB_ALLOCATION" MODIFY ("ALLOCATION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."SUB_ALLOCATION" MODIFY ("BRANCH" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."SUB_ALLOCATION" MODIFY ("BATCH_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."SUB_ALLOCATION" MODIFY ("ENTITY_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."SUB_ALLOCATION" MODIFY ("ENTITY_TYPE_ID" NOT NULL ENABLE);
