--------------------------------------------------------
--  DDL for Table SUB_ALLOCATION
--------------------------------------------------------

  CREATE TABLE "HR"."SUB_ALLOCATION" 
   (	"BRANCH" VARCHAR2(10 BYTE), 
	"BATCH_ID" NUMBER, 
	"ENTITY_ID" NUMBER, 
	"ENTITY_TYPE_ID" NUMBER, 
	"REF_SUB_ID" NUMBER, 
	"IS_ACTIVE" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"REMARK" VARCHAR2(50 BYTE), 
	"ENT_DATE" DATE, 
	"ENT_TERM" VARCHAR2(20 BYTE), 
	"ENT_USER" VARCHAR2(20 BYTE), 
	"UPD_DATE" DATE, 
	"UPD_USER" VARCHAR2(20 BYTE), 
	"UPD_TERM" VARCHAR2(20 BYTE), 
	"TIME_STAMP" VARCHAR2(50 BYTE), 
	"ALLOCATION_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
