--------------------------------------------------------
--  Ref Constraints for Table SUB_ALLOCATION
--------------------------------------------------------

  ALTER TABLE "HR"."SUB_ALLOCATION" ADD CONSTRAINT "SUB_ALLOCATION_FK1" FOREIGN KEY ("REF_SUB_ID")
	  REFERENCES "HR"."SUB_MAS" ("SUB_ID") ENABLE;
 
  ALTER TABLE "HR"."SUB_ALLOCATION" ADD CONSTRAINT "SUB_ALLOCATION_FK_BATCH" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "HR"."BATCH_MAS" ("BATCH_ID") ENABLE;
 
  ALTER TABLE "HR"."SUB_ALLOCATION" ADD CONSTRAINT "SUB_ALLOCATION_FK_ID" FOREIGN KEY ("ENTITY_ID")
	  REFERENCES "HR"."ENTITY_MAS" ("ENTITY_ID") ENABLE;
 
  ALTER TABLE "HR"."SUB_ALLOCATION" ADD CONSTRAINT "SUB_ALLOCATION_FK_TYPE" FOREIGN KEY ("ENTITY_TYPE_ID")
	  REFERENCES "HR"."ENTITY_TYPE_MAS" ("ENTITY_TYPE_ID") ENABLE;
