--------------------------------------------------------
--  DDL for Table TEACHER_MAS
--------------------------------------------------------

  CREATE TABLE "HR"."TEACHER_MAS" 
   (	"TEACHER_ID" NUMBER, 
	"T_ENTITY_ID" NUMBER, 
	"T_FNAME" VARCHAR2(30 BYTE), 
	"T_MNAME" VARCHAR2(30 BYTE), 
	"T_LNAME" VARCHAR2(30 BYTE), 
	"SCHL_ID" NUMBER, 
	"EXPE" NUMBER, 
	"PH1" NUMBER, 
	"PH2" NUMBER, 
	"ADR" VARCHAR2(100 BYTE), 
	"REMARK" VARCHAR2(100 BYTE), 
	"ENT_DATE" DATE, 
	"ENT_USER" VARCHAR2(30 BYTE), 
	"ENT_TERM" VARCHAR2(30 BYTE), 
	"UPD_DATE" DATE, 
	"UPD_USER" VARCHAR2(30 BYTE), 
	"UPD_TERM" VARCHAR2(30 BYTE), 
	"TIME_STAMP" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "USERS" ;
