--------------------------------------------------------
--  Constraints for Table TEACHER_MAS
--------------------------------------------------------

  ALTER TABLE "HR"."TEACHER_MAS" MODIFY ("TEACHER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TEACHER_MAS" MODIFY ("T_ENTITY_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TEACHER_MAS" MODIFY ("PH1" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TEACHER_MAS" MODIFY ("ENT_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TEACHER_MAS" MODIFY ("ENT_USER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TEACHER_MAS" MODIFY ("ENT_TERM" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TEACHER_MAS" MODIFY ("TIME_STAMP" NOT NULL ENABLE);
