--------------------------------------------------------
--  Ref Constraints for Table TIMETABLE
--------------------------------------------------------

  ALTER TABLE "HR"."TIMETABLE" ADD CONSTRAINT "TIMETABLE_FK_BATCH_ID" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "HR"."BATCH_MAS" ("BATCH_ID") ENABLE;
 
  ALTER TABLE "HR"."TIMETABLE" ADD CONSTRAINT "TIMETABLE_FK_ENTITY_ID" FOREIGN KEY ("REF_T_ENTITY_ID")
	  REFERENCES "HR"."ENTITY_MAS" ("ENTITY_ID") ENABLE;
 
  ALTER TABLE "HR"."TIMETABLE" ADD CONSTRAINT "TIMETABLE_FK_SUB_ID" FOREIGN KEY ("REF_SUB_ID")
	  REFERENCES "HR"."SUB_MAS" ("SUB_ID") ENABLE;
