--------------------------------------------------------
--  DDL for Table TIMETABLE
--------------------------------------------------------

  CREATE TABLE "HR"."TIMETABLE" 
   (	"BRANCH" VARCHAR2(10 BYTE), 
	"BATCH_ID" NUMBER, 
	"T_DATE" DATE, 
	"FR_TIME" NUMBER, 
	"TO_TIME" NUMBER, 
	"REF_SUB_ID" NUMBER, 
	"REF_T_ENTITY_ID" NUMBER, 
	"ENT_DATE" DATE, 
	"ENT_TERM" VARCHAR2(20 BYTE), 
	"ENT_USER" VARCHAR2(20 BYTE), 
	"UPD_DATE" DATE, 
	"UPD_USER" VARCHAR2(20 BYTE), 
	"UPD_TERM" VARCHAR2(20 BYTE), 
	"TIME_STAMP" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
