--------------------------------------------------------
--  Constraints for Table TIMETABLE
--------------------------------------------------------

  ALTER TABLE "HR"."TIMETABLE" MODIFY ("BRANCH" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TIMETABLE" MODIFY ("BATCH_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TIMETABLE" MODIFY ("T_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TIMETABLE" MODIFY ("ENT_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TIMETABLE" MODIFY ("ENT_TERM" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TIMETABLE" MODIFY ("ENT_USER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TIMETABLE" MODIFY ("TIME_STAMP" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TIMETABLE" ADD CONSTRAINT "TIMETABLE_UK1" UNIQUE ("BRANCH", "BATCH_ID", "T_DATE", "REF_SUB_ID", "REF_T_ENTITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
