--------------------------------------------------------
--  Constraints for Table TRANSACTION_SETTING
--------------------------------------------------------

  ALTER TABLE "HR"."TRANSACTION_SETTING" MODIFY ("ENT_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRANSACTION_SETTING" MODIFY ("ENT_TERM" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRANSACTION_SETTING" MODIFY ("ENT_USER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRANSACTION_SETTING" MODIFY ("TIME_STAMP" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRANSACTION_SETTING" MODIFY ("SEQNO" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRANSACTION_SETTING" ADD CONSTRAINT "TRANSACTION_SETTING_PK" PRIMARY KEY ("SEQNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."TRANSACTION_SETTING" ADD CONSTRAINT "TRANSACTION_SETTING_UK1" UNIQUE ("BATCH_ID", "REF_ENTITY_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
