--------------------------------------------------------
--  DDL for Table TRANSACTION_SETTING
--------------------------------------------------------

  CREATE TABLE "HR"."TRANSACTION_SETTING" 
   (	"BATCH_ID" NUMBER, 
	"REF_ENTITY_TYPE_ID" NUMBER, 
	"AMOUNT" NUMBER, 
	"CASH_CHQ_RATIO" NUMBER, 
	"ALLOW_EMI" VARCHAR2(1 BYTE), 
	"ALLOW_ADVANCE" VARCHAR2(1 BYTE), 
	"NO_OF_EMI" NUMBER, 
	"DISCOUNT" NUMBER, 
	"REMARK" VARCHAR2(50 BYTE), 
	"ENT_DATE" DATE, 
	"ENT_TERM" VARCHAR2(20 BYTE), 
	"ENT_USER" VARCHAR2(20 BYTE), 
	"UPD_DATE" DATE, 
	"UPD_USER" VARCHAR2(20 BYTE), 
	"UPD_TERM" VARCHAR2(20 BYTE), 
	"TIME_STAMP" TIMESTAMP (6), 
	"SEQNO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
