--------------------------------------------------------
--  Ref Constraints for Table TRANSACTION_SETTING
--------------------------------------------------------

  ALTER TABLE "HR"."TRANSACTION_SETTING" ADD CONSTRAINT "TRANSACTION_SETTING_FK_BATCH" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "HR"."BATCH_MAS" ("BATCH_ID") ENABLE;
 
  ALTER TABLE "HR"."TRANSACTION_SETTING" ADD CONSTRAINT "TRANSACTION_SETTING_FK_TYPE" FOREIGN KEY ("REF_ENTITY_TYPE_ID")
	  REFERENCES "HR"."ENTITY_TYPE_MAS" ("ENTITY_TYPE_ID") ENABLE;
