--------------------------------------------------------
--  DDL for Index UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."UK1" ON "HR"."EXAM_MAS" ("BATCH_ID", "REF_SUB_ID", "EXAM_DATE", "EXAM_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
